### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by shamsul007** [enggarsulistyo/BraviaEngine#1]
Is there a way to alter the settings to see the difference?

**Comment by enggarsulistyo** [comment]
I don't think there is anything for that
but the changes will be obvious from the capture of the image and home screen
try capturing images with objects that are the same as or without bravia

**Comment by hengkidermawan** [comment]
there will be lots of testers and input if you open this tread at XDA, I think

**Comment by enggarsulistyo** [comment]
> there will be lots of testers and input if you open this tread at XDA, I think

great idea
but I don't have an xda account
I will try to make it for that
thanks
