### ISSUE TITLE
Can't use on XZ2

### ISSUE THREAD

**Issue by Chiyoda0913** [enggarsulistyo/BraviaEngine#2]
Maybe it can't be used on Sony stock rom?

**Comment by enggarsulistyo** [comment]
For sony xz2 stockrom alredy installed bravia

**Comment by Chiyoda0913** [comment]
But it will lose after unlock the bootloader.😅

Enggar Sulistyo <notifications@github.com> 於 2018年12月21日 週五 上午10:49寫道：

**Comment by enggarsulistyo** [comment]
I think it supports
