### ISSUE TITLE
youtube always animation loading

### ISSUE THREAD

**Issue by CoffeeNen** [enggarsulistyo/BraviaEngine#5]
aftee instal bravia engine 4.0.3 youtube cant play always animation loading 
![Screenshot_20200822-235920_YouTube_Vanced](https://user-images.githubusercontent.com/68474108/90961477-893e1100-e4d3-11ea-9958-8e3423df3d99.png)

**Comment by enggarsulistyo** [comment]
https://user-images.githubusercontent.com/20156902/153769447-c56c2764-6786-42a3-870b-7fe1d1f1c95f.mp4

For me

**Comment by enggarsulistyo** [comment]
https://user-images.githubusercontent.com/20156902/153769567-9b31c46e-c974-4f26-b231-e8314fc1cba0.mp4


https://user-images.githubusercontent.com/20156902/153769582-638ffd09-de1a-41d4-a921-19ab8003c73a.mp4

All normal for me
