### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by nikotidar** [enggarsulistyo/BraviaEngine#7]
Installation Failed on Magisk 25.1 on Xiaomi Redmi Note 10 Pro.

![Screenshot_2022-07-14-16-01-47-765_com topjohnwu magisk](https://user-images.githubusercontent.com/49534825/178945461-f9fe986c-a389-4736-bd38-08f0086ee8b3.jpg)

![Screenshot_2022-07-14-16-01-54-331_com topjohnwu magisk](https://user-images.githubusercontent.com/49534825/178945489-fac3eefc-b06c-4210-a750-d0b15baedf31.jpg)

Is Xiaomi supported?

**Comment by MijLmao** [comment]
Installation success on Xperia 1 IV but it results a bootloop.

**Comment by enggarsulistyo** [comment]
> Installation Failed on Magisk 25.1 on Xiaomi Redmi Note 10 Pro.
> 
> ![Screenshot_2022-07-14-16-01-47-765_com topjohnwu magisk](https://user-images.githubusercontent.com/49534825/178945461-f9fe986c-a389-4736-bd38-08f0086ee8b3.jpg)
> 
> ![Screenshot_2022-07-14-16-01-54-331_com topjohnwu magisk](https://user-images.githubusercontent.com/49534825/178945489-fac3eefc-b06c-4210-a750-d0b15baedf31.jpg)
> 
> Is Xiaomi supported?

modul template not support magisk update, lastest update template only support magisk 15.x

**Comment by enggarsulistyo** [comment]
> Installation success on Xperia 1 IV but it results a bootloop.

Your device has Bravia installed from the manufacturer sony
